### ISSUE TITLE
Type instead of Enum?

### ISSUE THREAD

**Issue by CKGrafico** [dennismorello/react-awesome-reveal#20]
Why there are types like export type Direction = 'top' | 'left' | 'bottom' | 'right' | undefined; that cannot be used as enum?

that means we cannot do something like that, can we?

```
<Fade direction={Direction.Bottom}>
```

**Comment by dennismorello** [comment]
Hi @CKGrafico,

the reason why I export a type and not an enum is because users (especially plain JS developers) can easily use autocompletions without having to import the Direction transpiled member ([documentation](https://www.typescriptlang.org/docs/handbook/enums.html)). I could write it as a `const enum`, but I don't think this would make the developer experience that better ;)
