### ISSUE TITLE
Not working in Safari

### ISSUE THREAD

**Issue by Gauraklein** [dennismorello/react-awesome-reveal#29]
Hi, really like the library. Just wanted to share a bug I've found. It seems the library doesn't work properly in Safari. The error I'm getting is attached below. Tested on IOS 13 as well as desktop safari version 12.0.1.

<img width="1277" alt="Screen Shot 2020-06-17 at 9 49 14 AM" src="https://user-images.githubusercontent.com/45526226/84913166-d7700780-b07f-11ea-9a64-d222d2dd2a17.png">

**Comment by dennismorello** [comment]
Hi @Gauraklein, react-awesome-reveal uses the Intersection Observer API in order to detect when elements enter the viewport. Make sure to enable the support for this API from Safari settings (under Experimental Features):

![image](https://user-images.githubusercontent.com/19588613/84913774-2be4a880-b0bb-11ea-9a65-762524d8ad38.jpeg)

It should work properly after this change.


Cheers

**Comment by dennismorello** [comment]
https://caniuse.com/#feat=intersectionobserver

**Comment by Gauraklein** [comment]
Oh awesome! Thanks @dennismorello
