### ISSUE TITLE
Is this a fork of react-reveal?

### ISSUE THREAD

**Issue by averyfreeman** [dennismorello/react-awesome-reveal#33]
Hi,

I was just wondering, is this a fork of `react-reveal`? I'm tentatively  looking for a replacement.  `react-reveal` is great, but it hasn't been maintained in 3 years, and it's giving me this warning I can't seem to make go away:

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. . . . Please update the following components: RevealBase
```

I added `UNSAFE_` to the library but one of my components which requires the `when={useStateParam)` stopped working afterward.  Would `react-awesome-reveal` be a valid replacement in this instance?

Thanks

**Comment by dennismorello** [comment]
Hi @averyfreeman,

this library is not a fork of ‘react-reveal’ and it is not intended to have an API compatibile with it.

It uses modern techniques to bring most of the ‘react-reveal’ features to React apps but I have never planned to port 1:1 the feature that library has.

By the way, more cool stuff is coming to ‘react-awesome-reveal’, and since it is open source everyone can share ideas and improve the library by submitting PRs!

**Comment by averyfreeman** [comment]
I appreciate the clarification!  I'm going to look into adopting it as a replacement since it's under active development.

The only consideration I have at the moment is if there's a substitute for `when` that will allow me to pass a boolean for `useState()`, as I'm currently using `react-reveal` for sliding in/out my mobile drawer.

Thanks,
Avery

**Comment by dennismorello** [comment]
> I appreciate the clarification!  I'm going to look into adopting it as a replacement since it's under active development.
> 
> 
> 
> The only consideration I have at the moment is if there's a substitute for `when` that will allow me to pass a boolean for `useState()`, as I'm currently using `react-reveal` for sliding in/out my mobile drawer.
> 
> 
> 
> Thanks,
> 
> Avery

There is already an issue for that, see #14.
