### ISSUE TITLE
Pulse causes error

### ISSUE THREAD

**Issue by BroFox86** [dennismorello/react-awesome-reveal#42]
Pulse animation causes error in my create-react-app template. Other animations work well.

Code:

```
import React from "react";
import { setPageInfo } from "../../helpers/setPageInfo";
import { MainLayout } from "../../layouts/MainLayout";
import { Pulse } from "react-awesome-reveal";

export function Animations() {

  setPageInfo( "Animations", "This is animation sandbox." );
 
  return(
    <MainLayout>
      
      <section>
        <Pulse> 
          <h1>Pulse animation</h1>
        </Pulse>
      </section>

    </MainLayout>
  )
}
```

<img width="455" alt="Снимок экрана 2020-09-03 в 16 10 14" src="https://user-images.githubusercontent.com/23554264/92119272-3e3fca00-ee00-11ea-8e31-3d9ca1c91f66.png">

**Comment by dennismorello** [comment]
Hi @BroFox86, since version 3 all attention seeker animations are wrapped by the `AttentionSeeker` component, which accept a prop named `effect` that specifies the animation you want to render: `"bounce"  | "flash"  | "headShake"  | "heartBeat"  | "jello"  | "pulse"  | "rubberBand"  | "shake"  | "shakeX"  | "shakeY"  | "swing"  | "tada"  | "wobble"`.

In your case, you have to refactor your code to:

```jsx
import React from "react";
import { setPageInfo } from "../../helpers/setPageInfo";
import { MainLayout } from "../../layouts/MainLayout";
import { AttentionSeeker } from "react-awesome-reveal";

export function Animations() {
  setPageInfo( "Animations", "This is animation sandbox." );

  return (
    <MainLayout>
      <section>
        <AttentionSeeker effect="pulse">
          <h1>Pulse animation</h1>
        </AttentionSeeker>
      <section>
    </MainLayout>
  );
}
```

Let me know if it fixes your issue.

**Comment by BroFox86** [comment]
It works! Thank you!
