### ISSUE TITLE
Request: Override fade-in direction distance

### ISSUE THREAD

**Issue by Johnhersh** [dennismorello/react-awesome-reveal#43]
Love this package, it helps out my project a lot!
It would be awesome if I can control the distance elements travel when using Fade with a direction. I'm using Fade with Left and the elements always seem to fly in from off-screen. It would be super helpful if I could override that distance with a set pixel amount,

**Comment by dennismorello** [comment]
Hi @Johnhersh,

this would be a customization of the default [`fadeInLeft`](https://github.com/dennismorello/react-awesome-reveal/blob/master/src/animations/fading_entrances/fadeInLeft.ts) animation. Since the parameters of that animation are defined inside the `@keyframes` CSS rule, is not possible to do any customization at the moment.

Broadly speaking, what you are looking for is a way to define generic animations, and this could be one of the next features of `react-awesome-reveal`, so... Stay tuned for updates!

**Comment by dennismorello** [comment]
Hi @Johnhersh, that's a good issue!

You can customize the animations by importing the `Reveal` component (which is the default export of the library, starting from version 3.2.0) and by passing it a custom `keyframes` prop:

```jsx
import React from "react";
import { keyframes } from "@emotion/core";
import Reveal from "react-awesome-reveal";

const customAnimation = keyframes`
  from {
    opacity: 0;
    transform: translate3d(-200px, 0, 0);
  }
  to {
    opacity: 1;
    transform: translate3d(0, 0, 0);
  }
`;

function MyAnimatedComponent({children}) {
  return (
    <Reveal keyframes={customAnimation}>
      {children}
    </Reveal>;
  );
}
`;
```

Cheers!

**Comment by dennismorello** [comment]
[Documentation](https://github.com/dennismorello/react-awesome-reveal#custom-animations) added.
